<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdddoctrineRecordAbstract extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doctrine__record__abstract', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doctrine__record__abstract');
    }
}