<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('page_layout', 'page_layout_template_id_template_id', array(
             'name' => 'page_layout_template_id_template_id',
             'local' => 'template_id',
             'foreign' => 'id',
             'foreignTable' => 'template',
             ));
        $this->createForeignKey('page_layout', 'page_layout_page_id_page_id', array(
             'name' => 'page_layout_page_id_page_id',
             'local' => 'page_id',
             'foreign' => 'id',
             'foreignTable' => 'page',
             ));
        $this->createForeignKey('page_layout', 'page_layout_admin_content_type_id_admin_content_type_id', array(
             'name' => 'page_layout_admin_content_type_id_admin_content_type_id',
             'local' => 'admin_content_type_id',
             'foreign' => 'id',
             'foreignTable' => 'admin_content_type',
             ));
        $this->createForeignKey('page_layout', 'page_layout_admin_section_id_admin_section_id', array(
             'name' => 'page_layout_admin_section_id_admin_section_id',
             'local' => 'admin_section_id',
             'foreign' => 'id',
             'foreignTable' => 'admin_section',
             ));
        $this->createForeignKey('page_layout', 'page_layout_admin_table_id_admin_table_id', array(
             'name' => 'page_layout_admin_table_id_admin_table_id',
             'local' => 'admin_table_id',
             'foreign' => 'id',
             'foreignTable' => 'admin_table',
             ));
        $this->createForeignKey('template_section', 'template_section_admin_section_id_admin_section_id', array(
             'name' => 'template_section_admin_section_id_admin_section_id',
             'local' => 'admin_section_id',
             'foreign' => 'id',
             'foreignTable' => 'admin_section',
             ));
        $this->createForeignKey('template_section', 'template_section_template_id_template_id', array(
             'name' => 'template_section_template_id_template_id',
             'local' => 'template_id',
             'foreign' => 'id',
             'foreignTable' => 'template',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('page_layout', 'page_layout_template_id_template_id');
        $this->dropForeignKey('page_layout', 'page_layout_page_id_page_id');
        $this->dropForeignKey('page_layout', 'page_layout_admin_content_type_id_admin_content_type_id');
        $this->dropForeignKey('page_layout', 'page_layout_admin_section_id_admin_section_id');
        $this->dropForeignKey('page_layout', 'page_layout_admin_table_id_admin_table_id');
        $this->dropForeignKey('template_section', 'template_section_admin_section_id_admin_section_id');
        $this->dropForeignKey('template_section', 'template_section_template_id_template_id');
    }
}