<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpagelayout extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('page_layout', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'item' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'admin_content_type_id' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 45,
             ),
             'page_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'admin_table_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'admin_section_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'template_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'section_seq' => 
             array(
              'type' => 'integer',
              'default' => 1,
              'length' => 4,
             ),
             'item_seq' => 
             array(
              'type' => 'integer',
              'default' => 1,
              'length' => 4,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'layoutindex' => 
              array(
              'fields' => 
              array(
               0 => 'page_id',
               1 => 'admin_table_id',
               2 => 'template_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('page_layout');
    }
}