<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AffiliateProduct', 'admin');

/**
 * Admin_Model_Base_AffiliateProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $productid
 * @property string $product_name
 * @property string $description
 * @property string $deeplink
 * @property decimal $price
 * @property string $image_url
 * @property string $last_updated
 * @property string $related_products
 * @property string $related_product_ids
 * @property string $additionalproductdetails
 * @property string $brand
 * @property string $currency
 * @property string $country
 * @property decimal $delivery_cost
 * @property string $delivery_period
 * @property decimal $display_price
 * @property string $barcode
 * @property string $embargo
 * @property timestamp $expiry_at
 * @property string $image_large_url
 * @property string $image_thumbnail_url
 * @property string $language
 * @property string $promotion_details
 * @property string $qanda
 * @property string $review
 * @property string $short_description
 * @property integer $stock_level
 * @property timestamp $stock_level_date_at
 * @property string $best_sellers
 * @property string $type
 * @property string $mobile_network
 * @property string $contract_type
 * @property string $contract_length
 * @property string $inclusive_minutes
 * @property string $inclusive_texts
 * @property string $data_allowance
 * @property string $network_promotion
 * @property string $service_provider
 * @property string $stock_code
 * @property string $basket_url
 * @property decimal $handset_price
 * @property integer $in_stock
 * @property string $warranty
 * @property string $item_condition
 * @property string $offer_type
 * @property string $bid
 * @property string $model_number
 * @property integer $affiliate_product_category_id
 * @property integer $affiliate_network_id
 * @property integer $affiliate_retailer_id
 * @property string $specification
 * @property decimal $rrp_price
 * @property string $isbn
 * @property integer $pre_order
 * @property integer $web_offer
 * @property timestamp $valid_from
 * @property timestamp $valid_to
 * @property string $product_type
 * @property integer $ean
 * @property decimal $search_price
 * @property integer $is_hot_pick
 * @property string $unique_hash
 * @property Admin_Model_AffiliateRetailer $AffiliateRetailer
 * @property Admin_Model_AffiliateProductCategory $AffiliateProductCategory
 * @property Admin_Model_AffiliateNetwork $AffiliateNetwork
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AffiliateProduct extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('affiliate_product');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('productid', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('product_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('deeplink', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('price', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => '10',
             ));
        $this->hasColumn('image_url', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('last_updated', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('related_products', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('related_product_ids', 'string', 2048, array(
             'type' => 'string',
             'length' => '2048',
             ));
        $this->hasColumn('additionalproductdetails', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('brand', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('currency', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('country', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('delivery_cost', 'decimal', 15, array(
             'type' => 'decimal',
             'length' => '15',
             ));
        $this->hasColumn('delivery_period', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('display_price', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => '10',
             ));
        $this->hasColumn('barcode', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('embargo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('expiry_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('image_large_url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('image_thumbnail_url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('language', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('promotion_details', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('qanda', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('review', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('short_description', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('stock_level', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('stock_level_date_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('best_sellers', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('type', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('mobile_network', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('contract_type', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('contract_length', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('inclusive_minutes', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('inclusive_texts', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('data_allowance', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('network_promotion', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('service_provider', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('stock_code', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('basket_url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('handset_price', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => '10',
             ));
        $this->hasColumn('in_stock', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('warranty', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('item_condition', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('offer_type', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('bid', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('model_number', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('affiliate_product_category_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '8',
             ));
        $this->hasColumn('affiliate_network_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('affiliate_retailer_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('specification', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('rrp_price', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => '10',
             ));
        $this->hasColumn('isbn', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('pre_order', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('web_offer', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('valid_from', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('valid_to', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('product_type', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('ean', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('search_price', 'decimal', 25, array(
             'type' => 'decimal',
             'length' => '25',
             ));
        $this->hasColumn('is_hot_pick', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('unique_hash', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));


        $this->index('hash_index', array(
             'fields' => 
             array(
              'unique_hash' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AffiliateRetailer as AffiliateRetailer', array(
             'local' => 'affiliate_retailer_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AffiliateProductCategory as AffiliateProductCategory', array(
             'local' => 'affiliate_product_category_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AffiliateNetwork as AffiliateNetwork', array(
             'local' => 'affiliate_network_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $blameable0 = new Doctrine_Template_Blameable();
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($softdelete0);
        $this->actAs($blameable0);
    }
}