<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_PageHeader', 'admin');

/**
 * Admin_Model_Base_PageHeader
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Admin_Model_Page $Page
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_PageHeader extends Admin_Model_PageFooter
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('page_header');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Page as Page', array(
             'local' => 'id',
             'foreign' => 'page_header_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}