
<span class="copy"> <input type="hidden" id="site-dir"
	value="<?php echo SITE_DIR; ?>" /> powered by &copy; <a
	href="http://www.rhema-webdesign.com">rhema webdesign</a> - all rights
reserved. Valid XHTML &amp; CSS. </span>
<div id="ajax-loading" style="display: none; text-align: center"
	title="Please wait">
<ul>
	<li>&nbsp;</li>
</ul>
<span class="wait-image">&nbsp;</span></div>
<div id="info-div" style="display: none"><span id="user-role"><?php echo strtolower(Zend_Registry::get('user-role')); ?></span>
</div>